org.gradle.caching=true
org.gradle.jvmargs='-Dfile.encoding=UTF-8'
group=org.ballerinax.datamapper
version=2.2.1-SNAPSHOT
systemProp.org.gradle.internal.publish.checksums.insecure=true
ballerinaLangVersion=2201.14.0-20260527-050400-74f7e6bf
ballerinaGradlePluginVersion=4.0.0
stdlibIoVersion=1.8.0

puppycrawlCheckstyleVersion=10.12.0
githubSpotbugsVersion=6.5.1
jacocoVersion=0.8.14
downloadVersion=5.4.0
researchgateReleaseVersion=3.1.0

observeVersion=1.5.0
observeInternalVersion=1.5.0
